/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAL.ChuongTrinhHocDAL;
import DAL.HocVienDAL;
import DTO.ChuongTrinhHocDTO;
import DTO.HocVienDTO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tran Lam Khanh Tuong
 */
public class MaHinhChuongTrinhHoc extends javax.swing.JFrame {

    /**
     * Creates new form MaHinhChuongTrinhHoc
     */
    
    
    String dieukien=null;
    public MaHinhChuongTrinhHoc() {
        initComponents();
        TaiDsChuongTrinhHoc();
        jtbChuongTrinhHoc.setRowSelectionInterval(0, 0);
        jtbChuongTrinhHoc.setDefaultEditor(Object.class, null);
        btnLuuLai.setEnabled(false);
        btnCapNhat.setEnabled(false);
        txtTenChuongTrinhHoc.setEnabled(false);
        txtHocPhi.setEnabled(false);
        btnXoa.setEnabled(false);
    }
    
    private DefaultTableModel tblModel = new DefaultTableModel();
    
     private void TaiDsChuongTrinhHoc()
    {
        ChuongTrinhHocDAL chuongtrinhhocdal = new ChuongTrinhHocDAL();
        String header[] = {"Mã Chương Trình Học", "Tên Chương Trình Học", "Học Phí"};
        tblModel.setColumnIdentifiers(header);
        tblModel.setRowCount(0);
        ArrayList<ChuongTrinhHocDTO> li = new ArrayList<ChuongTrinhHocDTO>();
        li = chuongtrinhhocdal.LayDanhSachChuongTrinhHoc();
        for(ChuongTrinhHocDTO cth : li)
        {
            Vector data =new Vector();
            
            data.add(cth.getMachuongtrinhhoc());
            data.add(cth.getTenchuongtrinhoc());
            data.add(cth.getHocphi());

            tblModel.addRow(data);
        }
        jtbChuongTrinhHoc.setModel(tblModel);
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbChuongTrinhHoc = new javax.swing.JTable();
        btnTiemKiem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnLuuLai = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenChuongTrinhHoc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHocPhi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTimKiem.setToolTipText("");

        jtbChuongTrinhHoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtbChuongTrinhHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtbChuongTrinhHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbChuongTrinhHocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbChuongTrinhHoc);

        btnTiemKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTiemKiem.setText("Tìm kiếm");
        btnTiemKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiemKiemActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thao Tác", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 153, 153))); // NOI18N

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLuuLai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLuuLai.setText("Lưu lại");
        btnLuuLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuLaiActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Thoát");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem)
                .addGap(67, 67, 67)
                .addComponent(btnCapNhat)
                .addGap(68, 68, 68)
                .addComponent(btnXoa)
                .addGap(64, 64, 64)
                .addComponent(btnLuuLai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnCapNhat)
                    .addComponent(btnXoa)
                    .addComponent(btnLuuLai)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin Chương trình học", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(153, 153, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tên chương trình học:");

        txtTenChuongTrinhHoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Học phí:");

        txtHocPhi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHocPhi)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addComponent(txtTenChuongTrinhHoc))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(txtTenChuongTrinhHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addComponent(txtHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("QUẢN LÝ CHƯƠNG TRÌNH HỌC");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 0));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTiemKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTiemKiem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnTiemKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiemKiemActionPerformed
        // TODO add your handling code here:
          if (txtTimKiem.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập chương trình học cần tìm");
        }
        else
        {
            TimChuongTrinhHoc(txtTimKiem.getText().toString().trim());
        }
        
        
    }//GEN-LAST:event_btnTiemKiemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int ret = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa mục này ?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (ret != JOptionPane.YES_OPTION) {
            return;
        }
        ChuongTrinhHocDAL cthdal = new ChuongTrinhHocDAL();
        jtbChuongTrinhHoc.getSelectedColumn();
        
        ret=cthdal.XoaTheoMa(dieukien);
        if(ret!=-1)
        {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            txtTenChuongTrinhHoc.setText("");
            txtHocPhi.setText("");
            TaiDsChuongTrinhHoc();
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Xóa không thành công");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jtbChuongTrinhHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbChuongTrinhHocMouseClicked
        // TODO add your handling code here:
                btnCapNhat.setEnabled(true);
                btnXoa.setEnabled(true);
        txtTenChuongTrinhHoc.setEnabled(true);
        txtHocPhi.setEnabled(true);
        int index= jtbChuongTrinhHoc.getSelectedRow();
        dieukien=jtbChuongTrinhHoc.getModel().getValueAt(index, 0).toString();
        txtTenChuongTrinhHoc.setText(jtbChuongTrinhHoc.getModel().getValueAt(index, 1).toString());
        txtHocPhi.setText(jtbChuongTrinhHoc.getModel().getValueAt(index, 2).toString());
        
        
    }//GEN-LAST:event_jtbChuongTrinhHocMouseClicked

    private void btnLuuLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuLaiActionPerformed
        // TODO add your handling code here:

        
        int ret = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm chương trình học ?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (ret != JOptionPane.YES_OPTION) {
            return;
        }
        ChuongTrinhHocDAL cthdal = new ChuongTrinhHocDAL();

        
        ret=cthdal.ThemCTH(txtTenChuongTrinhHoc.getText().toString().trim(),Long.parseLong(txtHocPhi.getText().toString().trim()));
        if(ret!=-1)
        {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            txtTenChuongTrinhHoc.setText("");
            txtHocPhi.setText("");
            btnLuuLai.setEnabled(false);
            btnCapNhat.setEnabled(false);
            txtTenChuongTrinhHoc.setEnabled(false);
            txtHocPhi.setEnabled(false);
            btnXoa.setEnabled(false);
            btnThem.setEnabled(true);
            TaiDsChuongTrinhHoc();
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Thêm không thành công");
        }
        
        
              
    }//GEN-LAST:event_btnLuuLaiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
            txtTenChuongTrinhHoc.setText("");
            txtHocPhi.setText("");
            btnLuuLai.setEnabled(true);
            btnThem.setEnabled(false);
            btnCapNhat.setEnabled(false);
            btnXoa.setEnabled(false);
            txtTenChuongTrinhHoc.setEnabled(true);
            txtHocPhi.setEnabled(true);
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
                int ret = JOptionPane.showConfirmDialog(this, "Bạn có muốn cập nhật chương trình học ?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (ret != JOptionPane.YES_OPTION) {
            return;
        }
        ChuongTrinhHocDAL cthdal = new ChuongTrinhHocDAL();
        int index= jtbChuongTrinhHoc.getSelectedRow();
        //int dieukien=jtbChuongTrinhHoc.getModel().getValueAt(index, 0).toString();
        cthdal.CapNhatCTH(dieukien,txtTenChuongTrinhHoc.getText().toString().trim(),Long.parseLong(txtHocPhi.getText().toString().trim()));
        if(ret!=-1)
        {
            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            txtTenChuongTrinhHoc.setText("");
            txtHocPhi.setText("");
            btnLuuLai.setEnabled(false);
            btnCapNhat.setEnabled(false);
            txtTenChuongTrinhHoc.setEnabled(false);
            txtHocPhi.setEnabled(false);
            btnXoa.setEnabled(false);
            btnThem.setEnabled(true);
            TaiDsChuongTrinhHoc();
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại. Vui lòng kiểm tra lại");
        }
        
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void TimChuongTrinhHoc(String dieukien)
    {
        
        ChuongTrinhHocDAL chuongtrinhhocdal = new ChuongTrinhHocDAL();
        String header[] = {"Mã Chương Trình Học", "Tên Chương Trình Học", "Học Phí"};
        tblModel.setColumnIdentifiers(header);
        tblModel.setRowCount(0);
        ArrayList<ChuongTrinhHocDTO> li = new ArrayList<ChuongTrinhHocDTO>();
        li = chuongtrinhhocdal.TimChuongTrinhHocTheoTen(dieukien);
        for(ChuongTrinhHocDTO cth : li)
        {
            Vector data =new Vector();
            
            data.add(cth.getMachuongtrinhhoc());
            data.add(cth.getTenchuongtrinhoc());
            data.add(cth.getHocphi());
            tblModel.addRow(data);
        }
        jtbChuongTrinhHoc.setModel(tblModel);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaHinhChuongTrinhHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaHinhChuongTrinhHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaHinhChuongTrinhHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaHinhChuongTrinhHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaHinhChuongTrinhHoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuuLai;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTiemKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jtbChuongTrinhHoc;
    private javax.swing.JTextField txtHocPhi;
    private javax.swing.JTextField txtTenChuongTrinhHoc;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
