/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAL.CTPCDAL;
import DAL.NhanVienDAL;
import DAL.PhieuChiDAL;
import DTO.CTPCDTO;
import DTO.NhanVienDTO;
import DTO.PhieuChiDTO;
import java.awt.event.ItemEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;
import java.util.Date;

/**
 *
 * @author Tran Lam Khanh Tuong
 */
public class ManHinhPhieuXuat extends javax.swing.JFrame {

    /**
     * Creates new form ManHinhPhieuXuat
     */
    public ManHinhPhieuXuat() {
        initComponents();
        LoadDuLieuNhanVien();
        Date date = new Date();
        jdcNgayChi.setDate(date);
        jdcNgayBatDau.setDate(date);
        jdcNgayKetThuc.setDate(date);
        LoadDanhSachPhieuChi();
        jtbDanhSachPhieuChi.setRowSelectionInterval(0, 0);
        jtbDanhSachPhieuChi.setDefaultEditor(Object.class, null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbNhanVienPhieuXuat = new javax.swing.JComboBox();
        btnTimKiemPhieuChi = new javax.swing.JButton();
        jdcNgayBatDau = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jdcNgayKetThuc = new com.toedter.calendar.JDateChooser();
        btnMoTabThemPhieuChiMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDanhSachPhieuChi = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblTenNhanVien = new javax.swing.JLabel();
        lblNgayChi = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtbDanhMucChi = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        btnMoTabThemPhieuChiMoi1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cmbNhanVienPhieuXuatLPC = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jdcNgayChi = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbCTPC = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTienMucDichChi = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaMucDichChi = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnThemDanhMucChi = new javax.swing.JButton();
        btnLamMoiPhieuChi = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel1.setForeground(new java.awt.Color(51, 102, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 0));
        jLabel1.setText("Chọn ngày bắt đầu:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 0));
        jLabel2.setText("Nhân viên:");

        cmbNhanVienPhieuXuat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbNhanVienPhieuXuat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNhanVienPhieuXuatItemStateChanged(evt);
            }
        });

        btnTimKiemPhieuChi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTimKiemPhieuChi.setForeground(new java.awt.Color(0, 153, 0));
        btnTimKiemPhieuChi.setText("Tìm kiếm");
        btnTimKiemPhieuChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemPhieuChiActionPerformed(evt);
            }
        });

        jdcNgayBatDau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 0));
        jLabel5.setText("Chọn ngày kết thúc:");

        jdcNgayKetThuc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnMoTabThemPhieuChiMoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMoTabThemPhieuChiMoi.setForeground(new java.awt.Color(0, 153, 0));
        btnMoTabThemPhieuChiMoi.setText("Lập phiếu chi mới");
        btnMoTabThemPhieuChiMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoTabThemPhieuChiMoiActionPerformed(evt);
            }
        });

        jtbDanhSachPhieuChi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtbDanhSachPhieuChi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtbDanhSachPhieuChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDanhSachPhieuChiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbDanhSachPhieuChi);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdcNgayBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(97, 97, 97)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cmbNhanVienPhieuXuat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdcNgayKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))))
                        .addGap(53, 53, 53)
                        .addComponent(btnTimKiemPhieuChi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(btnMoTabThemPhieuChiMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdcNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTimKiemPhieuChi)
                        .addComponent(btnMoTabThemPhieuChiMoi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jdcNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbNhanVienPhieuXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tìm kiếm phiếu chi", jPanel1);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Tên Nhân Viên: ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Ngày chi:");

        lblTenNhanVien.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTenNhanVien.setText("Tên Nhân Viên: ");

        lblNgayChi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNgayChi.setText("Ngày chi:");

        jtbDanhMucChi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtbDanhMucChi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jtbDanhMucChi);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 0));
        jLabel12.setText("Danh mục chi");

        btnMoTabThemPhieuChiMoi1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMoTabThemPhieuChiMoi1.setForeground(new java.awt.Color(0, 153, 0));
        btnMoTabThemPhieuChiMoi1.setText("Lập phiếu chi mới");
        btnMoTabThemPhieuChiMoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoTabThemPhieuChiMoi1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(46, 46, 46)
                        .addComponent(lblTenNhanVien)
                        .addGap(161, 161, 161)
                        .addComponent(jLabel11)
                        .addGap(50, 50, 50)
                        .addComponent(lblNgayChi)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(313, 313, 313))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnMoTabThemPhieuChiMoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(lblTenNhanVien)
                    .addComponent(lblNgayChi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMoTabThemPhieuChiMoi1)
                .addGap(4, 4, 4))
        );

        jTabbedPane1.addTab("Thông tin phiếu chi", jPanel2);

        cmbNhanVienPhieuXuatLPC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbNhanVienPhieuXuatLPC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNhanVienPhieuXuatLPCItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 153));
        jLabel3.setText("Nhân viên");

        jdcNgayChi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 153));
        jLabel4.setText("Chọn ngày");

        jtbCTPC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtbCTPC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mục đích", "Tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtbCTPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbCTPCMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbCTPC);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 153));
        jLabel6.setText("Mục đích chi");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 153));
        jLabel7.setText("Tiền");

        txtTienMucDichChi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTienMucDichChi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTienMucDichChiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTienMucDichChiKeyTyped(evt);
            }
        });

        jtaMucDichChi.setColumns(20);
        jtaMucDichChi.setRows(5);
        jScrollPane3.setViewportView(jtaMucDichChi);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 0));
        jLabel8.setText("Danh mục chi");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thao tác", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jButton3.setBackground(new java.awt.Color(102, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Thoát");

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Lập phiếu chi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnThemDanhMucChi.setBackground(new java.awt.Color(102, 0, 0));
        btnThemDanhMucChi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThemDanhMucChi.setText("Thêm danh mục chi");
        btnThemDanhMucChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDanhMucChiActionPerformed(evt);
            }
        });

        btnLamMoiPhieuChi.setBackground(new java.awt.Color(102, 0, 0));
        btnLamMoiPhieuChi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLamMoiPhieuChi.setText("Làm mới");
        btnLamMoiPhieuChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiPhieuChiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemDanhMucChi)
                .addGap(56, 56, 56)
                .addComponent(jButton2)
                .addGap(73, 73, 73)
                .addComponent(btnLamMoiPhieuChi)
                .addGap(82, 82, 82)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnThemDanhMucChi)
                    .addComponent(btnLamMoiPhieuChi)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTienMucDichChi, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                .addComponent(jdcNgayChi, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3))
                            .addComponent(cmbNhanVienPhieuXuatLPC, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(141, 141, 141))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbNhanVienPhieuXuatLPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdcNgayChi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTienMucDichChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lập phiếu chi", jPanel3);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel9.setText("QUẢN LÝ CHI");

        jSeparator1.setForeground(new java.awt.Color(102, 102, 0));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(265, 265, 265))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private DefaultTableModel tblModel = new DefaultTableModel();
    private DefaultTableModel tblModel_2 = new DefaultTableModel();

    private void TimPhieuChi(String ngaybatdau, String ngayketthuc, String ten) {

        PhieuChiDAL phieuchidal = new PhieuChiDAL();
        String header[] = {"Mã phiếu chi", "Tên nhân viên", "Ngày"};
        tblModel.setColumnIdentifiers(header);
        tblModel.setRowCount(0);
        ArrayList<PhieuChiDTO> li = new ArrayList<PhieuChiDTO>();
        li = phieuchidal.TimKiemPhieuChi(ngaybatdau, ngayketthuc, ten);
        for (PhieuChiDTO px : li) {
            Vector data = new Vector();
            data.add(px.getMaphieuchi());
            data.add(px.getManv());
            data.add(px.getNgay());

            tblModel.addRow(data);
        }
        jtbDanhSachPhieuChi.setModel(tblModel);

    }

    private void btnTimKiemPhieuChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemPhieuChiActionPerformed

        SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd");
        String ngaybd = dcn.format(jdcNgayBatDau.getDate());
        System.out.print(dcn.format(jdcNgayBatDau.getDate()));
        String ngaykt = dcn.format(jdcNgayKetThuc.getDate());
        System.out.print(dcn.format(jdcNgayKetThuc.getDate()));
        TimPhieuChi(ngaybd, ngaykt, manv);
    }//GEN-LAST:event_btnTimKiemPhieuChiActionPerformed

    String manv;
    private void cmbNhanVienPhieuXuatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNhanVienPhieuXuatItemStateChanged
        // TODO add your handling code here:

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            NhanVienDTO cbm = (NhanVienDTO) cmbNhanVienPhieuXuat.getSelectedItem();
            manv = cbm.getManhanvien();
        }
    }//GEN-LAST:event_cmbNhanVienPhieuXuatItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        PhieuChiDAL phieuchidal = new PhieuChiDAL();

        java.util.Date utilStartDate = jdcNgayChi.getDate();
        java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());

        int ret = JOptionPane.showConfirmDialog(this, "Bạn có muốn lập phiếu chi ?", "Confirm", JOptionPane.YES_NO_OPTION);

        if (ret != JOptionPane.YES_OPTION) {
            return;
        }

        String maphieuchi = String.valueOf(System.currentTimeMillis());
        ret = phieuchidal.ThemPhieuChi(maphieuchi, manvchi, sqlStartDate);

        CTPCDAL ctpcdal = new CTPCDAL();
        //int rows=jtbCTPC.getRowCount();
        int kt;
        int kt2 = 0;
        System.out.print("So hang:");
        System.out.print(jtbCTPC.getRowCount());
        for (int i = 0; i < jtbCTPC.getRowCount(); i++) {

            String noidung = (String) jtbCTPC.getValueAt(i, 0);
            long tien = (long) jtbCTPC.getValueAt(i, 1);
            //System.out.print(tien);
            System.out.print(noidung);
            System.out.print(tien);
            kt = ctpcdal.ThemCTPC(maphieuchi, noidung, tien);
            if (kt != -1) {
                kt2 = i;
                System.out.print("thm thanh cong");
            }

        }

        if (ret != -1 && kt2 == jtbCTPC.getRowCount() - 1) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");

        } else {
            JOptionPane.showMessageDialog(this, "Thêm không thành công");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    String manvchi;
    private void cmbNhanVienPhieuXuatLPCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNhanVienPhieuXuatLPCItemStateChanged
        // TODO add your handling code here:

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            NhanVienDTO cbm = (NhanVienDTO) cmbNhanVienPhieuXuat.getSelectedItem();
            manvchi = cbm.getManhanvien();
        }
    }//GEN-LAST:event_cmbNhanVienPhieuXuatLPCItemStateChanged

    private void LoadDanhSachPhieuChi() {
        PhieuChiDAL phieuchidal = new PhieuChiDAL();
        String header[] = {"Mã phiếu chi", "Tên nhân viên", "Ngày"};
        tblModel.setColumnIdentifiers(header);
        tblModel.setRowCount(0);
        ArrayList<PhieuChiDTO> li = new ArrayList<PhieuChiDTO>();
        li = phieuchidal.LayDanhSachPhieuChi();
        for (PhieuChiDTO px : li) {
            Vector data = new Vector();
            data.add(px.getMaphieuchi());
            data.add(px.getManv());
            data.add(px.getNgay());

            tblModel.addRow(data);
        }
        jtbDanhSachPhieuChi.setModel(tblModel);

    }

    private void btnThemDanhMucChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDanhMucChiActionPerformed
        // TODO add your handling code here
        long tien=0;
        try
        {
            tien= Long.parseLong(txtTienMucDichChi.getText());
            DefaultTableModel tblModel_1 = (DefaultTableModel) jtbCTPC.getModel();
            tblModel_1.addRow(new Object[]{jtaMucDichChi.getText(),tien});
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Sai định dạng vui lòng kiểm tra lại");
        }
            
    }//GEN-LAST:event_btnThemDanhMucChiActionPerformed

    private void btnLamMoiPhieuChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiPhieuChiActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel_1 = (DefaultTableModel) jtbCTPC.getModel();
        tblModel_1.setRowCount(0);
        jtaMucDichChi.setText("");
        txtTienMucDichChi.setText("");
    }//GEN-LAST:event_btnLamMoiPhieuChiActionPerformed

    private void jtbCTPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbCTPCMouseClicked
        // TODO add your handling code here:
        int index = jtbCTPC.getSelectedRow();
        jtaMucDichChi.setText(jtbCTPC.getValueAt(index, 0).toString());
        txtTienMucDichChi.setText(jtbCTPC.getValueAt(index, 1).toString());
    }//GEN-LAST:event_jtbCTPCMouseClicked

    private void txtTienMucDichChiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienMucDichChiKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTienMucDichChiKeyPressed

    private void txtTienMucDichChiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienMucDichChiKeyTyped


    }//GEN-LAST:event_txtTienMucDichChiKeyTyped

    private void btnMoTabThemPhieuChiMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoTabThemPhieuChiMoiActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnMoTabThemPhieuChiMoiActionPerformed

    String maphieuchict;
    private void GetDataRow()
    {
        int index = jtbDanhSachPhieuChi.getSelectedRow();
        System.out.print(index);
        lblTenNhanVien.setText(jtbDanhSachPhieuChi.getValueAt(index, 1).toString());
        lblNgayChi.setText(jtbDanhSachPhieuChi.getValueAt(index, 2).toString());
        maphieuchict=jtbDanhSachPhieuChi.getValueAt(index, 0).toString();
        jTabbedPane1.setSelectedIndex(1);

        
    }
    
    private void jtbDanhSachPhieuChiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDanhSachPhieuChiMouseClicked
        // TODO add your handling code here:
        
       GetDataRow();
       TimChiTietPhieuChi(maphieuchict);
       

       
        

    }//GEN-LAST:event_jtbDanhSachPhieuChiMouseClicked

    private void btnMoTabThemPhieuChiMoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoTabThemPhieuChiMoi1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnMoTabThemPhieuChiMoi1ActionPerformed

        private void TimChiTietPhieuChi(String maphieuchict) {

        CTPCDAL ctpcdal = new CTPCDAL();
        String header[] = {"Nội dung", "Tiền"};
        tblModel_2.setColumnIdentifiers(header);
        tblModel_2.setRowCount(0);
        ArrayList<CTPCDTO> li = new ArrayList<CTPCDTO>();
        li =ctpcdal.TimKiemCTPC(maphieuchict);
        for (CTPCDTO ctpcdtp : li) {
            Vector data = new Vector();
            data.add(ctpcdtp.getNoidung());
            data.add(ctpcdtp.getTien());
            //data.add(px.getNgay());

            tblModel_2.addRow(data);
        }
        jtbDanhMucChi.setModel(tblModel_2);

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhPhieuXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhPhieuXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhPhieuXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhPhieuXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManHinhPhieuXuat().setVisible(true);
            }
        });

    }

    private void LoadDuLieuNhanVien() {

        cmbNhanVienPhieuXuat.removeAllItems();
        NhanVienDAL nvdal = new NhanVienDAL();
        ArrayList<NhanVienDTO> li = new ArrayList<NhanVienDTO>();
        li = nvdal.LayDanhSachNhanVien();
        for (NhanVienDTO lh : li) {
            cmbNhanVienPhieuXuat.addItem(lh);
            cmbNhanVienPhieuXuatLPC.addItem(lh);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoiPhieuChi;
    private javax.swing.JButton btnMoTabThemPhieuChiMoi;
    private javax.swing.JButton btnMoTabThemPhieuChiMoi1;
    private javax.swing.JButton btnThemDanhMucChi;
    private javax.swing.JButton btnTimKiemPhieuChi;
    private javax.swing.JComboBox cmbNhanVienPhieuXuat;
    private javax.swing.JComboBox cmbNhanVienPhieuXuatLPC;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jdcNgayBatDau;
    private com.toedter.calendar.JDateChooser jdcNgayChi;
    private com.toedter.calendar.JDateChooser jdcNgayKetThuc;
    private javax.swing.JTextArea jtaMucDichChi;
    private javax.swing.JTable jtbCTPC;
    private javax.swing.JTable jtbDanhMucChi;
    private javax.swing.JTable jtbDanhSachPhieuChi;
    private javax.swing.JLabel lblNgayChi;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JTextField txtTienMucDichChi;
    // End of variables declaration//GEN-END:variables
}
