/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAL.ChuongTrinhHocDAL;
import DAL.GiangVienDAL;
import DAL.HocVienDAL;
import DAL.HocVien_LopHocDAL;
import DAL.LopHocDAL;
import DAL.NhanVienDAL;
import DAL.PhieuThuDAL;
import DTO.ChuongTrinhHocDTO;
import DTO.HocVienDTO;
import DTO.LopHocDTO;
import DTO.NhanVienDTO;
import java.awt.event.ItemEvent;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tran Lam Khanh Tuong
 */
public class ManHinhGhiDanh extends javax.swing.JFrame {

    /**
     * Creates new form ManHinhGhiDanh
     */
    
    private DefaultTableModel tblModel = new DefaultTableModel();
    private String mahocvien;
    private String malophoc;
    private String tenlophoc;
    private String tenchuongtrinhhoc;
    private String machuongtrinhoc;
    private long hocphi;
    private String manv;
    
    
    
    public ManHinhGhiDanh() {
        initComponents();
        TaiDanhSachHocVien();
        jtbDanhSachHocVien.setRowSelectionInterval(0, 0);
        jtbDanhSachHocVien.setDefaultEditor(Object.class, null);
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
        
       
    }
    
    private void TaiDanhSachHocVien()
    {
        HocVienDAL hocviendal = new HocVienDAL();
        String header[] = {"Mã học viên", "Tên học viên", "Email", "Địa chỉ","SĐT"};
        tblModel.setColumnIdentifiers(header);
        tblModel.setRowCount(0);
        ArrayList<HocVienDTO> li = new ArrayList<HocVienDTO>();
        li = hocviendal.LayDanhSachHocVien();
        for(HocVienDTO hv : li)
        {
            Vector data =new Vector();
            
            data.add(hv.getMahocvien());
            data.add(hv.getTenhocvien());
            data.add(hv.getEmail());
            data.add(hv.getDiachi());
            data.add(hv.getSdt());
            tblModel.addRow(data);
        }
        jtbDanhSachHocVien.setModel(tblModel);
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDanhSachHocVien = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cmbChuongTrinhHoc = new javax.swing.JComboBox();
        lblDiaChi2 = new javax.swing.JLabel();
        lblHocPhi = new javax.swing.JLabel();
        lblDiaChi3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblNgayKetThuc = new javax.swing.JLabel();
        lblTenGiangVien = new javax.swing.JLabel();
        lblNgayBatDau = new javax.swing.JLabel();
        lblLoaiLopHoc = new javax.swing.JLabel();
        lblDiaChi10 = new javax.swing.JLabel();
        lblDiaChi13 = new javax.swing.JLabel();
        lblDiaChi6 = new javax.swing.JLabel();
        lblDiaChi4 = new javax.swing.JLabel();
        lblDiaChi9 = new javax.swing.JLabel();
        cmbLopHoc = new javax.swing.JComboBox();
        btnGhiDanh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        lblTenHocVienHoaDon = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbNhanVienHoaDon = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        lblTenLopHocHoaDon = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblTenChuongTrinhHocHoaDon = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSoTienTra = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        bntXuatHoaDon = new javax.swing.JButton();
        btnLuu1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jtbDanhSachHocVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtbDanhSachHocVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtbDanhSachHocVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDanhSachHocVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbDanhSachHocVien);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tìm kiếm học viên", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin học viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Địa chỉ:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tên: ");

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail.setText("Email:");

        lblTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTen.setText("Tên: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Số điện thoại:");

        lblSDT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSDT.setText("Số điện thoại:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Email:");

        lblDiaChi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDiaChi.setText("Địa chỉ:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiaChi)
                    .addComponent(lblTen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32)
                        .addComponent(lblSDT))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(lblEmail)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lblTen)
                    .addComponent(lblEmail))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(lblDiaChi)
                    .addComponent(lblSDT))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin chương trình học", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 51, 102))); // NOI18N

        cmbChuongTrinhHoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbChuongTrinhHoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbChuongTrinhHocItemStateChanged(evt);
            }
        });
        cmbChuongTrinhHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbChuongTrinhHocActionPerformed(evt);
            }
        });

        lblDiaChi2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDiaChi2.setText("Học phí:");

        lblHocPhi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHocPhi.setText("Học phí:");

        lblDiaChi3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDiaChi3.setText("Chọn Chương Trình Học ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDiaChi3)
                    .addComponent(lblDiaChi2))
                .addGap(92, 92, 92)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbChuongTrinhHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHocPhi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbChuongTrinhHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiaChi3))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaChi2)
                    .addComponent(lblHocPhi))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin Lớp học", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(153, 153, 0))); // NOI18N

        lblNgayKetThuc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNgayKetThuc.setText("Ngày kết thúc");

        lblTenGiangVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTenGiangVien.setText("Tên giảng viên:");

        lblNgayBatDau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNgayBatDau.setText("Ngày bắt đầu :");

        lblLoaiLopHoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLoaiLopHoc.setText("Chọn Lớp Học: ");

        lblDiaChi10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDiaChi10.setText("Ngày kết thúc:");

        lblDiaChi13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDiaChi13.setText("Tên giảng viên:");

        lblDiaChi6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDiaChi6.setText("Loại lớp học:");

        lblDiaChi4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDiaChi4.setText("Chọn Lớp Học: ");

        lblDiaChi9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDiaChi9.setText("Ngày bắt đầu :");

        cmbLopHoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbLopHoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbLopHocItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiaChi6)
                            .addComponent(lblDiaChi9)
                            .addComponent(lblDiaChi13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLoaiLopHoc)
                                    .addComponent(lblNgayBatDau))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDiaChi10)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(153, 153, 153)
                                        .addComponent(lblNgayKetThuc))))
                            .addComponent(lblTenGiangVien))
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblDiaChi4)
                        .addGap(120, 120, 120)
                        .addComponent(cmbLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiaChi4))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoaiLopHoc)
                    .addComponent(lblDiaChi6))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaChi9)
                    .addComponent(lblNgayBatDau)
                    .addComponent(lblDiaChi10)
                    .addComponent(lblNgayKetThuc))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaChi13)
                    .addComponent(lblTenGiangVien))
                .addGap(20, 20, 20))
        );

        btnGhiDanh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGhiDanh.setText("Ghi Danh");
        btnGhiDanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiDanhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(btnGhiDanh)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGhiDanh)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ghi Danh", jPanel2);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Thông tin hóa đơn");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tên học viên:");

        lblTenHocVienHoaDon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTenHocVienHoaDon.setText("Tên học viên:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Tên nhân viên:");

        cmbNhanVienHoaDon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbNhanVienHoaDon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNhanVienHoaDonItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Tên lớp học:");

        lblTenLopHocHoaDon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTenLopHocHoaDon.setText("Tên lớp học:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Chương trình học:");

        lblTenChuongTrinhHocHoaDon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTenChuongTrinhHocHoaDon.setText("Mã chương trình học:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Số tiền trả :");

        txtSoTienTra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSoTienTra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoTienTraKeyPressed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLuu.setText("Trở về màng hình chính");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        bntXuatHoaDon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bntXuatHoaDon.setText("Xuất hóa đơn");

        btnLuu1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLuu1.setText("Lưu");
        btnLuu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTenChuongTrinhHocHoaDon)
                            .addComponent(txtSoTienTra, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenLopHocHoaDon)
                            .addComponent(cmbNhanVienHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenHocVienHoaDon))))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLuu)
                .addGap(39, 39, 39)
                .addComponent(btnLuu1)
                .addGap(35, 35, 35)
                .addComponent(bntXuatHoaDon)
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTenHocVienHoaDon))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbNhanVienHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblTenLopHocHoaDon))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblTenChuongTrinhHocHoaDon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoTienTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(74, 74, 74)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(bntXuatHoaDon)
                    .addComponent(btnLuu1))
                .addGap(42, 42, 42))
        );

        jTabbedPane1.addTab("Thanh toán", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbDanhSachHocVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDanhSachHocVienMouseClicked
        // TODO add your handling code here:        
        GetDataRow();
        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setSelectedIndex(1);
        TaiCTH();
        
        
    }//GEN-LAST:event_jtbDanhSachHocVienMouseClicked

    private void TaiCTH()
    {
        ChuongTrinhHocDAL cthdal = new ChuongTrinhHocDAL();
        ArrayList<ChuongTrinhHocDTO> li = new ArrayList<ChuongTrinhHocDTO>();
        li = cthdal.LayDanhSachChuongTrinhHoc();
        for(ChuongTrinhHocDTO ct : li)
        {
          
            cmbChuongTrinhHoc.addItem(ct);
        }
        cmbChuongTrinhHoc.setSelectedIndex(0);        
    }
    
    private void GetDataRow()
    {
        int index = jtbDanhSachHocVien.getSelectedRow();
        System.out.print(index);
        lblTen.setText(jtbDanhSachHocVien.getValueAt(index, 1).toString());
        lblEmail.setText(jtbDanhSachHocVien.getValueAt(index, 2).toString());
        lblDiaChi.setText(jtbDanhSachHocVien.getValueAt(index, 3).toString());
        lblSDT.setText(jtbDanhSachHocVien.getValueAt(index, 4).toString());
        mahocvien= jtbDanhSachHocVien.getValueAt(index, 0).toString();
        
    }
    
    private void TaiLopHoc(String dieukien)
    {
        cmbLopHoc.removeAllItems();
        LopHocDAL lhdal = new LopHocDAL();
        ArrayList<LopHocDTO> li = new ArrayList<LopHocDTO>();
        li = lhdal.TimKiemLopHocTheoChuongTrinhHoc(dieukien);
        for(LopHocDTO lh : li)
        {
            cmbLopHoc.addItem(lh);
        }
  
    }
    
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        if (txtTimKiem.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập học viên cần tìm");
        }
        else
        {
            TimHocVien(txtTimKiem.getText().toString().trim());
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void cmbChuongTrinhHocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbChuongTrinhHocItemStateChanged

        if(evt.getStateChange()== ItemEvent.SELECTED)
        {
            ChuongTrinhHocDTO cth = (ChuongTrinhHocDTO)cmbChuongTrinhHoc.getSelectedItem();
            TaiLopHoc(cth.getMachuongtrinhhoc());
            lblHocPhi.setText(String.valueOf(cth.getHocphi()));
            hocphi=cth.getHocphi();
            tenchuongtrinhhoc=cth.getTenchuongtrinhoc();
            machuongtrinhoc=cth.getMachuongtrinhhoc();
            
        }

    }//GEN-LAST:event_cmbChuongTrinhHocItemStateChanged


    
    private void cmbChuongTrinhHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbChuongTrinhHocActionPerformed
        // TODO add your handling code here:
       //  if(evt.getStateChange()== ItemEvent.SELECTED)
        //{
            //ChuongTrinhHocDTO cth = (ChuongTrinhHocDTO)cmbChuongTrinhHoc.getSelectedItem();
            //System.out.print(cth.getMachuongtrinhhoc());
            //TaiLopHoc(cth.getMachuongtrinhhoc());
            //TaiLopHoc(cth.getTenchuongtrinhoc());
        //}
       

    }//GEN-LAST:event_cmbChuongTrinhHocActionPerformed

    private void cmbLopHocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbLopHocItemStateChanged

        GiangVienDAL gvdal = new GiangVienDAL();
        if(evt.getStateChange()== ItemEvent.SELECTED)
        {
            LopHocDTO cbm = (LopHocDTO)cmbLopHoc.getSelectedItem();
            lblNgayBatDau.setText(cbm.getNgaybatdau().toString());
            lblNgayKetThuc.setText(cbm.getNgayketthuc().toString());
            lblLoaiLopHoc.setText(cbm.getLoailophoc());
            lblTenGiangVien.setText(gvdal.TimGiangVien(cbm.getMagiaovien()).getTengiangvien());
            malophoc=cbm.getMalophoc();
            tenlophoc=cbm.getTenlophoc();

            
        }
    }//GEN-LAST:event_cmbLopHocItemStateChanged

    private void LoadDuLieuNhanVien()
    {
        
        cmbNhanVienHoaDon.removeAllItems();
        NhanVienDAL nvdal= new NhanVienDAL();
        ArrayList<NhanVienDTO> li = new ArrayList<NhanVienDTO>();
        li = nvdal.LayDanhSachNhanVien();
        for(NhanVienDTO lh : li)
        {
            cmbNhanVienHoaDon.addItem(lh);
        }
    }
    
    private void btnGhiDanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiDanhActionPerformed
        // TODO add your handling code here:
        
        int ret = JOptionPane.showConfirmDialog(this, "Bạn có muốn ghi danh ?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (ret != JOptionPane.YES_OPTION) {
            return;
        }
        HocVien_LopHocDAL hvlhdal = new HocVien_LopHocDAL();
        Date today=new Date(System.currentTimeMillis());
        ret= hvlhdal.GhiDanh(mahocvien, malophoc, today);
        if (ret != -1) {
                JOptionPane.showMessageDialog(this, "Đăng ký thành công");
                jTabbedPane1.setEnabledAt(2, true);
                LoadDuLieuChoTabHoaDon();
                jTabbedPane1.setSelectedIndex(2);
                
                     
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Đăng ký thất bại. Vui lòng kiểm tra lại");
        }
    }//GEN-LAST:event_btnGhiDanhActionPerformed

    void LoadDuLieuChoTabHoaDon()
    {
        lblTenHocVienHoaDon.setText(lblTen.getText());
        lblTenLopHocHoaDon.setText(tenlophoc);
        lblTenChuongTrinhHocHoaDon.setText(tenchuongtrinhhoc);
        LoadDuLieuNhanVien();
    }
    private void cmbNhanVienHoaDonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNhanVienHoaDonItemStateChanged
        // TODO add your handling code here:

        //NhanVienDTO cbm = (NhanVienDTO)cmbNhanVienHoaDon.getSelectedItem();
        //manhanvien=cbm.getManhanvien().toString();
           if(evt.getStateChange()== ItemEvent.SELECTED)
        {
           NhanVienDTO cbm = (NhanVienDTO)cmbNhanVienHoaDon.getSelectedItem();
            manv=cbm.getManhanvien();
        }
        

    }//GEN-LAST:event_cmbNhanVienHoaDonItemStateChanged

    private void txtSoTienTraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoTienTraKeyPressed
        // TODO add your handling code here:
        //if(evt.getKeyChar()<='a' )
    }//GEN-LAST:event_txtSoTienTraKeyPressed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        
        int ret = JOptionPane.showConfirmDialog(this, "Bạn có muốn lưu ?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (ret != JOptionPane.YES_OPTION) {
            return;
        }
        
        PhieuThuDAL phieuthudal = new PhieuThuDAL();
        long sotientra = Long.parseLong( txtSoTienTra.getText().toString().trim());
        long sotienthieu = (Long.parseLong(lblHocPhi.getText()) - sotientra);
        Date today=new Date(System.currentTimeMillis());
        phieuthudal.ThemPhieuThu(mahocvien, malophoc,manv,sotientra,sotienthieu,today );
        
         if (ret != -1) {
                JOptionPane.showMessageDialog(this, "Lưu thành công");        
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Lưu thất bại. Vui lòng kiểm tra lại");
        }
        //long sotienthieu = (Long.parseLong(lblHocPhi.getText()) - sotientra);
        //Date today=new Date(System.currentTimeMillis());
        //hoadonbus.ThemHoaDon(mahocvien, malophoc,machuongtrinhhoc,manhanvien, sotientra, sotienthieu, today);

    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnLuu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuu1ActionPerformed
        // TODO add your handling code here:
         int ret = JOptionPane.showConfirmDialog(this, "Bạn có muốn lưu ?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (ret != JOptionPane.YES_OPTION) {
            return;
        }
        
        PhieuThuDAL phieuthudal = new PhieuThuDAL();
        long sotientra = Long.parseLong( txtSoTienTra.getText().toString().trim());
        long sotienthieu = (Long.parseLong(lblHocPhi.getText()) - sotientra);
        Date today=new Date(System.currentTimeMillis());
        phieuthudal.ThemPhieuThu(mahocvien, malophoc,manv,sotientra,sotienthieu,today );
        
         if (ret != -1) {
                JOptionPane.showMessageDialog(this, "Lưu thành công");        
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Lưu thất bại. Vui lòng kiểm tra lại");
        }
        
    }//GEN-LAST:event_btnLuu1ActionPerformed

    private void TimHocVien(String dieukien)
    {
        
        HocVienDAL hocviendal = new HocVienDAL();
        String header[] = {"Mã học viên", "Tên học viên", "Email", "Địa chỉ"};
        tblModel.setColumnIdentifiers(header);
        tblModel.setRowCount(0);
        ArrayList<HocVienDTO> li = new ArrayList<HocVienDTO>();
        li = hocviendal.TimKiemHocVienTheoTen(dieukien);
        for(HocVienDTO hv : li)
        {
            Vector data =new Vector();
            
            data.add(hv.getMahocvien());
            data.add(hv.getTenhocvien());
            data.add(hv.getEmail());
            data.add(hv.getDiachi());
            tblModel.addRow(data);
        }
        jtbDanhSachHocVien.setModel(tblModel);
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhGhiDanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhGhiDanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhGhiDanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhGhiDanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManHinhGhiDanh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntXuatHoaDon;
    private javax.swing.JButton btnGhiDanh;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnLuu1;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox cmbChuongTrinhHoc;
    private javax.swing.JComboBox cmbLopHoc;
    private javax.swing.JComboBox cmbNhanVienHoaDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtbDanhSachHocVien;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblDiaChi10;
    private javax.swing.JLabel lblDiaChi13;
    private javax.swing.JLabel lblDiaChi2;
    private javax.swing.JLabel lblDiaChi3;
    private javax.swing.JLabel lblDiaChi4;
    private javax.swing.JLabel lblDiaChi6;
    private javax.swing.JLabel lblDiaChi9;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblHocPhi;
    private javax.swing.JLabel lblLoaiLopHoc;
    private javax.swing.JLabel lblNgayBatDau;
    private javax.swing.JLabel lblNgayKetThuc;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTenChuongTrinhHocHoaDon;
    private javax.swing.JLabel lblTenGiangVien;
    private javax.swing.JLabel lblTenHocVienHoaDon;
    private javax.swing.JLabel lblTenLopHocHoaDon;
    private javax.swing.JTextField txtSoTienTra;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
